export const INPUT_FOCUS ='InputFocus'
export const INPUT_BLUR = 'InputBlur'
export const CHANGE_LIST = 'change-list'
export const SEARCH_MOUSE_IN = 'searchMouseIn'
export const SEARCH_MOUSE_LEAVE = 'searchMouseLeave'
export const CHANGE_SEARCH_ITEM = 'changeSearchItem'